# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :deploy do
  desc "deploy a new ios build to App Store"
  get_certificates           # invokes cert
  get_provisioning_profile   # invokes sigh
  gym(
    scheme: "Runner",
    configuration: "Release",
    export_method: "app-store"
  )
  deliver(
    submit_for_review: false,
    skip_screenshots: true,
    skip_metadata: true,
    phased_release: false,
    automatic_release: true,
  )
end